services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_SOCKET_URL=ws://localhost:4000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - CACHE_REDIS_URL=redis://redis:6379/2
      - QUEUE_REDIS_URL=redis://redis:6379/1
      - CACHE_REDIS_DEFAULT_EXPIRY=5200
      - NODE_ENV=production
      - APP_NAME=DONDY_BACKEND
      - PORT=4000
      - DB_URL=mongodb://mongo:27017/dondy
      - OPENAI_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=sk-##### // REPLACE WITH YOUR OPENAI_API_KEY
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:8
    ports:
      - '6379:6379'

  mongo:
    image: mongo:8
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
